apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.name" . }}-env
  labels:
{{ include "backend.labels" . | indent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.app.secretKey | quote }}
  SQLALCHEMY_DATABASE_URI: {{ .Values.app.sqlalchemyDatabaseUri | quote }}
  ADMIN_USERNAME: {{ .Values.app.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.app.adminPassword | quote }}
  ADMIN_EMAIL: {{ .Values.app.adminEmail | quote }}
  ADMIN_FIRST_NAME: {{ .Values.app.adminFirstName | quote }}
  ADMIN_LAST_NAME: {{ .Values.app.adminLastName | quote }}
  CELERY_BROKER_URL: {{ .Values.app.celeryBrokerURL | quote }}
  CELERY_RESULT_BACKEND_URL: {{ .Values.app.celeryResultBackendURL }}