{{- if eq .Values.app.mode "app" }}
{{- if .Values.ingress.tls.enabled }}
{{- if not .Values.ingress.tls.secretAutoCreate }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets-tls"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.cert }}
  tls.key: {{ .Values.ingress.tls.key }}
{{- end }}
{{- end }}
{{- end }}