app:
  secretKey: "foaxae4aitahphaiFai8queisu1eikie3Ohf7yae9Mei1aezeejobie2zeil2are"
  sqlalchemyDatabaseUri: "postgresql+asyncpg://backend:backend-pass@postgres:5432/backend"
  adminUsername: "admin"
  adminPassword: "password"
  adminEmail: "admin@gmail.com"
  adminFirstName: "John"
  adminLastName: "Doe"
  celeryBrokerURL: "amqp://backend:password@rabbitmq:5672/backend"
  celeryResultBackendURL: "redis://@redis:6379/0"

ingress:
  enabled: true
  class: "default-class"
  host: "test.domain.com"
  path: "/"
  tls:
    enabled: false
    secretName: "backend-secrets-tls"
    certificateIssuerName: "issuer-dev"
    secretAutoCreate: true